os: linux
dist: xenial
language: python

jobs:
  include:
    - name: Python 2.7
      python: 2.7
      env: python_version=2.7

    - name: Python 3.6
      python: 3.6
      env: python_version=3.6

    - name: Python 3.7
      python: 3.7
      env: python_version=3.7

    - name: Python 3.8
      python: 3.8
      env: python_version=3.8

    - name: Python 3.9
      python: 3.9-dev
      env: python_version=3.9-dev

  allow_failures:
    - python: 3.9-dev

cache:
  directories:
    - $HOME/buildout-cache
    - $HOME/parts/node

env:
  jobs:
    - CONF_CFG=travis.cfg

install:
  - pip install -U pip isort
  - pip install -r requirements.txt
  - buildout -c $CONF_CFG annotate
  - buildout -N -t 3 -c $CONF_CFG

script:
  - bin/code-analysis
  - bin/test

after_success:
  - travis_wait 30 bin/createcoverage run bin/test
  - travis_wait 30 pip install coverage coveralls
  - travis_wait 30 coveralls
after_failure:
  - bin/flake8 --version
